spring.application.name=BackendSpringBootBots

spring.datasource.url=jdbc:postgresql://localhost:5432/bots_local
spring.datasource.username=postgres
spring.datasource.password=sus

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
jwt.secret=my_secret_key_very_long_32chars_ps